#+TITLE: An Emacs Configuration
#+AUTHOR: Khinshan Khan
#+PROPERTY: header-args :tangle init.el
#+STARTUP: overview
#+PRIORITIES: A D B

* Preface

  After using emacs for a while (since my first programming class in high school), I decided to create my own
  configuration which I can use on most (if not any) machine. I'm still working on creating checks to ensure smooth
  runs, but Windows has proven to be sightly difficult with the package manager.

  For more information about myself, you can visit my website.

  This configuration is based on various emacs tips, users, and emacs itself (yes! You can talk to emacs to learn
  from it. Super classy move with =C-h [key such as f or v]=, since it's self documenting).

  A special thanks to my Emacs crew: [[https://github.com/Lgneous]["lgneous"]], [[https://github.com/Dreameh]["dreameh"]], and [[https://github.com/berquist]["speckledlemon"]].

  And some credit to some big name configs/ people which inspired me: [[https://github.com/hlissner/doom-emacs][Doom Emacs]], [[https://github.com/seagle0128/.emacs.d][Centaur Emacs]], [[https://github.com/purcell][purcell]].

* Pre-Configuration

  This code should be executed first. It's general, but will make the rest of the configuration nicer since it's
  somewhat 'meta'.

#+INCLUDE: "./modules/pre-config.org"

* Package Setup

#+INCLUDE: "./modules/package-setup.org"

* Tricks n Gimmicks for Sweeter Configuration

  General nice configuration to have. It'll help with later in the config.

#+INCLUDE: "./modules/tricks-n-gimmicks.org"

* Start Up

#+INCLUDE: "./modules/start-up.org"

* Appearance

#+INCLUDE: "./modules/appearance.org"

* Frontends

#+INCLUDE: "./modules/frontends.org"

* General Editing

  These guys are almost always active and a series of small things that have become second nature by now.

#+INCLUDE: "./modules/general-editing.org"

* Version Control

#+INCLUDE: "./modules/version-control.org"

* Programming Environment

#+INCLUDE: "./modules/programming-environment.org"

* Projects

#+INCLUDE: "./modules/projects.org"

* Programming Languages

  Editors are meant to actually edit code right?

#+INCLUDE: "./modules/language/asm.org"
#+INCLUDE: "./modules/language/c-cpp.org"
#+INCLUDE: "./modules/language/clojure.org"
#+INCLUDE: "./modules/language/dart-flutter.org"
#+INCLUDE: "./modules/language/elixir.org"
#+INCLUDE: "./modules/language/golang.org"
#+INCLUDE: "./modules/language/haskell.org"
#+INCLUDE: "./modules/language/java.org"
#+INCLUDE: "./modules/language/jupyter.org"
# #+INCLUDE: "./modules/language/kotlin.org"
#+INCLUDE: "./modules/language/lisp.org"
#+INCLUDE: "./modules/language/lua.org"
#+INCLUDE: "./modules/language/ocaml.org"
#+INCLUDE: "./modules/language/python.org"
#+INCLUDE: "./modules/language/r-julia.org"
# #+INCLUDE: "./modules/language/scala.org"
#+INCLUDE: "./modules/language/shell.org"
# #+INCLUDE: "./modules/language/swift.org"

* TODO Web Development

  Ara ara, “web development” is huge… let’s make it a first level bullet.

#+INCLUDE: "./modules/web-development.org"

* Other Programming

  Not quite a programming language, but more for tools.

#+INCLUDE: "./modules/other-programming.org"

* Org

  Org is so colossal, it’s worth learning. Gets its own file, and one day I’ll get around to making this literate and clean.

#+INCLUDE: "./modules/org.org"

* Language Augmentation

#+INCLUDE: "./modules/language-augmentation.org"

* Writing/ Documents

#+INCLUDE: "./modules/writing-n-documents.org"

* Hobbies

#+INCLUDE: "./modules/hobbies.org"

* Community

  A lot of vanity

#+INCLUDE: "./modules/community.org"

* TODO [#A] Miscellaneous Packages

  Just a salmagundi. Sooner or later, they'll find their places (or maybe their place here...).

  Problematic packages first, tangled off and commented.

# #+INCLUDE: "./modules/misc.org"
