#+TITLE: An Emacs Configuration
#+AUTHOR: Khinshan Khan
#+STARTUP: overview

* Preface

* Tricks n Gimmicks for Sweeter Configuration

Mostly just useful variables and functions.

** Personal Variables

Me, myself, and I.

These are personal preferences for emacs file structure.

#+BEGIN_SRC emacs-lisp
(defconst custom-file "/dev/zero")
(defconst shan/settings-path (concat user-emacs-directory "personal/settings.el"))
(defconst shan/settings-exist (file-exists-p shan/settings-path))
#+END_SRC

A couple of booleans so we don't have to check everytime.

#+BEGIN_SRC emacs-lisp
(when shan/settings-exist
  (load-file shan/settings-path))
#+END_SRC

Personal favored variables

#+BEGIN_SRC emacs-lisp
(setq vc-follow-symlinks nil)
(defconst shan/preferred-logo "personal/hifumi-sweater-emacs.png")
#+END_SRC

Shorthands

#+BEGIN_SRC emacs-lisp
(defconst shan/init-path (concat user-emacs-directory "init.el"))
(defconst shan/config-path (concat user-emacs-directory "config.org"))
#+END_SRC

** General Functions

Personal functions, some packages are reliant on these, so it goes on top. Working on credit for people not mentioned in preface and significant enough. Functions are split into... "sensible" groups. 

#+BEGIN_QUOTE
 [[[https://emacs.stackexchange.com/a/340][Credit: scratch]]]
 [[[https://stackoverflow.com/questions/95631/open-a-file-with-su-sudo-inside-emacs/7043786][Credit: sudo-edit]]]
 [[[https://github.com/purcell/emacs.d/blob/master/lisp/init-utils.el#L40-L48][Credit: delete-this-file]]]
 [[[https://github.com/purcell/emacs.d/blob/master/lisp/init-utils.el#L51-L65][Credit: rename-this-file-and-buffer]]]
 [[[https://github.com/purcell/emacs.d/blob/master/lisp/init-utils.el#L67-L77][Credit: browse-current-file]]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
(defun shan/do-nothing ()
  "Do nothing."
  (interactive)
  nil)

(defun shan/before (to-call-before f)
  "Run TO-CALL-BEFORE then run F."
  (funcall to-call-before)
  (funcall f))

(defun shan/after (to-call-after f)
  "Run F then run TO-CALL-AFTER."
  (funcall f)
  (funcall to-call-after))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun shan/split-window-right ()
  "Create a new window split to the right and balance the windows."
  (interactive)
  (shan/after #'balance-windows #'split-window-right))

(defun shan/split-window-below ()
  "Create a new window split below and balance the windows."
  (interactive)
  (shan/after #'balance-windows #'split-window-below))

(defun shan/delete-window ()
  "Delete the current window and balance the windows."
  (interactive)
  (shan/after #'balance-windows #'delete-window))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun shan/delete-buffer ()
  "Delete the current buffer and go to next most recent buffer."
  (interactive)
  (ido-kill-buffer))

(defun shan/refresh-buffer ()
  "Refresh the current buffer."
  (interactive)
  (revert-buffer :ignore-auto :noconfirm))

(defun shan/scratch ()
  "Create a new scratch buffer to work in. (could be *scratch* - *scratchX*)"
  (interactive)
  (let ((n 0) bufname)
    (while (progn
             (setq bufname (concat "*scratch"
                                   (if (= n 0) "" (int-to-string n))
                                   "*"))
             (setq n (1+ n))
             (get-buffer bufname)))
    (switch-to-buffer (get-buffer-create bufname))
    (lisp-interaction-mode)))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun shan/toggle-mark ()
  "Pop a mark if one doesn't exist already, deactivate it otherwise."
  (interactive)
  (if (region-active-p)
      (deactivate-mark)
    (push-mark nil nil t)))

(defun shan/toggle-mark-rectangle ()
  "Pop a rectangle mark if one doesn't exist already, deactivate it otherwise."
  (interactive)
  (if (region-active-p)
      (deactivate-mark)
    (rectangle-mark-mode)))
#+END_SRC

#+BEGIN_SRC emacs-lisp

(defun shan/first-occurence (f list)
  "Return the first occurence in LIST which, when applied to PREDICATE returns t."
  (let ((head (car list))
        (tail (cdr list)))
    (if (or (not head) (funcall f head))
        head
      (shan/first-occurence f tail))))

(defun shan/last-occurence (predicate list)
  "Return the last occurence in LIST which, when applied to PREDICATE returns t."
  (shan/first-occurence predicate (reverse list)))

(defmacro shan/find-executables (list)
  "Return the first occurence in LIST whose value corresponds to an executable."
  (shan/first-occurence #'executable-find list))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun shan/sudo-edit (file-name)
  "Like find file, but opens the file as root."
  (interactive "FSudo Find File: ")
  (let ((tramp-file-name (concat "/sudo::" (expand-file-name file-name))))
    (find-file tramp-file-name)))

(defun shan/delete-this-file ()
  "Delete the current file, and kill the buffer."
  (interactive)
  (unless (buffer-file-name)
    (error "No file is currently being edited"))
  (when (yes-or-no-p (format "Really delete '%s'?"
                             (file-name-nondirectory buffer-file-name)))
    (delete-file (buffer-file-name))
    (kill-this-buffer)))

(defun shan/rename-this-file-and-buffer (new-name)
  "Renames both current buffer and file it's visiting to NEW-NAME."
  (interactive "sNew name: ")
  (let ((name (buffer-name))
        (filename (buffer-file-name)))
    (unless filename
      (error "Buffer '%s' is not visiting a file!" name))
    (progn
      (when (file-exists-p filename)
        (rename-file filename new-name 1))
      (set-visited-file-name new-name)
      (rename-buffer new-name))))

(defun shan/browser-current-file ()
  "Open the current file as a URL using `browse-url'."
  (interactive)
  (let ((file-name (buffer-file-name)))
    (if (and (fboundp 'tramp-tramp-file-p)
             (tramp-tramp-file-p file-name))
        (error "Cannot open tramp file")
      (browse-url (concat "file://" file-name)))))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun shan/fill-or-unfill ()
  "Fill or unfill based on the previous command."
  (interactive)
  (let ((fill-column
         (if (eq last-command 'endless/fill-or-unfill)
             (progn (setq this-command nil)
                    (point-max))
           fill-column)))
    (call-interactively #'fill-paragraph)))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun shan/add-list-to-list (to-list from-list &optional append compare-fn)
  "Adds all elements from from-list to to-list"
  (dolist (elem from-list)
    (add-to-list to-list elem append compare-fn))
  to-list)

(defun shan/copy-hooks-to (from-hook to-hook)
  "Copies one list of hooks to another, without the weird nonc circular list problem"
  (dolist (hook from-hook)
    (add-hook to-hook hook)))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(defun shan/reload ()
  "Reload the configuration file."
  (interactive)
  (load-file shan/init-path))

(defun shan/edit-config ()
  "Edit the configuration file."
  (interactive)
  (find-file shan/config-path))
#+END_SRC

* Initialization

** Package Archives

Special commands, should always be needed. Note the algorithm is a hotfix to a much larger [[https://debbugs.gnu.org/cgi/bugreport.cgi?bug=34341][emacs issue]].

#+BEGIN_SRC emacs-lisp
(require 'package)
;; (setq package-enable-at-startup nil)
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
#+END_SRC

Set up all the archive sources to pull from packages from.

#+BEGIN_SRC emacs-lisp
(shan/add-list-to-list 'package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
					   ("melpa" . "http://melpa.org/packages/")
					   ("melpa-stable" . "http://stable.melpa.org/packages/")
					   ("melpa-stable2" . "http://melpa-stable.milkbox.net/packages/")
					   ("org" . "https://orgmode.org/elpa/"))
		       t)
(package-initialize)
#+END_SRC

** Package Installers

[[https://github.com/jwiegley/use-package][use-package]] configuration. Helps clean up rest of the configuration and speeds up startup
by isolating packages. The [[https://github.com/larstvei/Try][try]] package lets you try packages before installing them.

#+BEGIN_SRC emacs-lisp
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

(use-package use-package
  :config
  (setq-default use-package-always-defer nil
		use-package-always-ensure t
		use-package-always-demand t))

(setq-default byte-compile-warnings nil)

(use-package use-package-ensure-system-package)

(use-package try)
#+END_SRC

* Start Up


** Encoding

Begone utf 16!

#+BEGIN_SRC emacs-lisp
(setq-default locale-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
#+END_SRC

** Backups

I don't particularly need backup files, and =~= + =#= files are a pain to clean anyways.

#+BEGIN_SRC emacs-lisp
(setq-default backup-inhibited t
	      auto-save-default nil
	      create-lockfiles nil
	      make-backup-files nil)
#+END_SRC

** Version Specific

Weird errors of GTK without this.

#+BEGIN_SRC emacs-lisp
(when (>= emacs-major-version 26)
  (setq-default confirm-kill-processes nil))
#+END_SRC

** GUI

You need to experience keyboard to realize keyboard master race. (fn + f10 if need be for options though)

#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-message t)

(when (display-graphic-p)
  (menu-bar-mode 0)
  (toggle-scroll-bar 0)
  (tool-bar-mode 0))
#+END_SRC

* Org

#+BEGIN_SRC emacs-lisp
(use-package org
  :mode
  ("\\.\\(org\\|ORG\\)\\'" . org-mode)
  :ensure nil
  :hook
  (org-babel-after-execute . org-redisplay-inline-images)
  :custom
  (org-file-apps
   '((auto-mode . emacs)
     ("\\.x?html?\\'" . "/usr/bin/firefox -private-window %s")
     ("\\.pdf\\(::[0-9]+\\)?\\'" . "epdfview %s")))

  (org-directory "~/.orgfiles")
  (org-default-notes-file (concat org-directory "/notes.org"))
  (org-export-html-postamble nil)

  (org-image-actual-width 480)
  (org-src-fontify-natively t)
  (org-src-window-setup 'current-window)
  (org-src-strip-leading-and-trailing-blank-lines t)
  (org-src-preserve-indentation t)
  (org-src-tab-acts-natively t)
  (org-pretty-entities t)
  (org-hide-emphasis-markers t)
  (org-startup-with-inline-images t)
  (org-babel-python-command "ipython3 -i --simple-prompt")
  (org-format-latex-options (plist-put org-format-latex-options :scale 1.4))

  (org-plantuml-jar-path "/usr/share/java/plantuml/plantuml.jar")
  (org-ditaa-jar-path "/usr/share/java/ditaa/ditaa-0.11.jar")
  :config
  (add-to-list 'org-structure-template-alist
               '("el" "#+BEGIN_SRC emacs-lisp\n?\n#+END_SRC"))

  (use-package ob-ipython)

  (org-babel-do-load-languages
   'org-babel-load-languages
   '((ditaa      . t)
     (dot        . t)
     (emacs-lisp . t)
     (gnuplot    . t)
     (js         . t)
     (latex      . t)
     (ocaml      . t)
     (org        . t)
     (plantuml   . t)
     (python     . t)
     (shell      . t)
     (R          . t)
     ))

  (add-to-list 'org-src-lang-modes
               '("plantuml" . fundamental)))

(use-package toc-org
  :after org
  :hook
  (org-mode . toc-org-enable))

(use-package org-bullets
  :hook
  (org-mode . org-bullets-mode))

(use-package px)

(use-package htmlize)

(use-package ox-gfm
  :after (org))

(use-package ox-pandoc)
#+END_SRC
