;;; Automatically generated by ‘recentf’ on Sun Jan 30 14:23:37 2022.

(setq recentf-list
      '(
        "/home/shan/dotfiles/polybar/.config/polybar/config"
        "/home/shan/dotfiles/polybar/.config/polybar/launch.sh"
        "/etc/X11/xorg.conf.d/30-touchpad.conf"
        "/etc/X11/xorg.conf.d/00-keyboard.conf"
        "/home/shan/dotfiles/i3/.config/i3/config"
        "/home/shan/dotfiles/i3/.config/i3/scripts/get-current-brightnessctl"
        "/home/shan/dotfiles/i3/.config/i3/scripts/fetch-cfg-value"
        "/home/shan/Documents/aur.txt"
        "/home/shan/.emacs.d/var/url/cookies.el"
        "/home/shan/dotfiles/i3/.config/i3/scripts/powermenu"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
