#!/usr/bin/env bash

PICTURE=/tmp/i3lock.png
# TODO: change fetch-cfg-value reference once script is moved out of this repo
WALLPAPER=$(/usr/bin/env bash ~/.config/i3/scripts/fetch-cfg-value ~/.config/nitrogen/bg-saved.cfg xin_-1 file)

cp $WALLPAPER $PICTURE

RESOLUTION=$(xrandr -q|sed -n 's/.*current[ ]\([0-9]*\) x \([0-9]*\),.*/\1x\2/p')
BLUR="5x4"
convert $PICTURE -resize $RESOLUTION -blur $BLUR $PICTURE

i3lock -i $PICTURE
rm $PICTURE
